# Generated by Django 5.0.1 on 2024-03-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolcleanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskping',
            options={'managed': True},
        ),
    ]
