# Generated by Django 4.2.6 on 2024-03-30 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poolcleanapp", "0002_alter_taskping_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("card_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "expdate",
                    models.DateField(blank=True, db_column="ExpDate", null=True),
                ),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "payment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PoolcleanappClient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "clientname",
                    models.CharField(
                        blank=True, db_column="clientName", max_length=200, null=True
                    ),
                ),
                (
                    "addressline",
                    models.CharField(
                        blank=True, db_column="addressLine", max_length=200, null=True
                    ),
                ),
                (
                    "postalcode",
                    models.CharField(
                        blank=True, db_column="postalCode", max_length=10, null=True
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        blank=True, db_column="phoneNumber", max_length=100, null=True
                    ),
                ),
                (
                    "emailaddress",
                    models.CharField(
                        blank=True, db_column="emailAddress", max_length=100, null=True
                    ),
                ),
                (
                    "uniqueid",
                    models.CharField(
                        blank=True, db_column="uniqueId", max_length=100, null=True
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "poolcleanapp_client",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PoolcleanappInvoice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "duedate",
                    models.DateField(blank=True, db_column="dueDate", null=True),
                ),
                (
                    "paymentterms",
                    models.CharField(db_column="paymentTerms", max_length=100),
                ),
                ("status", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "uniqueid",
                    models.CharField(
                        blank=True, db_column="uniqueId", max_length=100, null=True
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "poolcleanapp_invoice",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PoolcleanappService",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "uniqueid",
                    models.CharField(
                        blank=True, db_column="uniqueId", max_length=100, null=True
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "poolcleanapp_service",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PoolcleanappSettings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "clientname",
                    models.CharField(
                        blank=True, db_column="clientName", max_length=200, null=True
                    ),
                ),
                (
                    "addressline",
                    models.CharField(
                        blank=True, db_column="addressLine", max_length=200, null=True
                    ),
                ),
                (
                    "postalcode",
                    models.CharField(
                        blank=True, db_column="postalCode", max_length=10, null=True
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        blank=True, db_column="phoneNumber", max_length=100, null=True
                    ),
                ),
                (
                    "emailaddress",
                    models.CharField(
                        blank=True, db_column="emailAddress", max_length=100, null=True
                    ),
                ),
                (
                    "uniqueid",
                    models.CharField(
                        blank=True, db_column="uniqueId", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "poolcleanapp_settings",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.AddField(
            model_name="taskping",
            name="c_id",
            field=models.ForeignKey(
                blank=True,
                db_column="C_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="poolcleanapp.company",
            ),
        ),
        migrations.AddField(
            model_name="taskping",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="poolcleanapp.client",
            ),
        ),
        migrations.AddField(
            model_name="taskping",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="taskping",
            name="status",
            field=models.CharField(
                choices=[("n", "In progress"), ("y", "Completed")],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="taskping",
            name="taskname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name="appointments",
            table="appointments",
        ),
        migrations.AlterModelTable(
            name="client",
            table="client",
        ),
        migrations.AlterModelTable(
            name="company",
            table="company",
        ),
        migrations.AlterModelTable(
            name="employee",
            table="employee",
        ),
    ]
