# Generated by Django 4.2.6 on 2024-02-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "poolcleanapp",
            "0002_appointments_company_employee_payment_taskping_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="client",
            table="CLIENT",
        ),
    ]
