# Generated by Django 5.0.1 on 2024-02-01 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "poolcleanapp",
            "0002_appointments_company_employee_payment_taskping_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="client",
            table="CLIENT",
        ),
    ]
