# Generated by Django 5.0.2 on 2024-04-06 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poolcleanapp", "0002_alter_taskping_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"managed": True},
        ),
        migrations.AddField(
            model_name="taskping",
            name="c_id",
            field=models.ForeignKey(
                blank=True,
                db_column="C_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="poolcleanapp.company",
            ),
        ),
        migrations.AddField(
            model_name="taskping",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="poolcleanapp.client",
            ),
        ),
        migrations.AddField(
            model_name="taskping",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="taskping",
            name="status",
            field=models.CharField(
                choices=[("n", "In progress"), ("y", "Completed")],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="taskping",
            name="taskname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name="appointments",
            table="appointments",
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1000)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "cl",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="poolcleanapp.client",
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="poolcleanapp.employee",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poolcleanapp.chatroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderAvailableTimes",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("appdate", models.DateField(blank=True, null=True)),
                ("apptime", models.TimeField(blank=True, null=True)),
                (
                    "c_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="poolcleanapp.company",
                    ),
                ),
            ],
            options={
                "db_table": "PROVIDERAVAILABLETIMES",
                "managed": True,
            },
        ),
    ]
