# Generated by Django 5.0.2 on 2024-04-07 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "poolcleanapp",
            "0003_chatroom_alter_client_options_alter_company_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="c",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="poolcleanapp.company",
            ),
        ),
    ]
