# Generated by Django 5.0.2 on 2024-04-07 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poolcleanapp", "0004_employee_c"),
    ]

    operations = [
        migrations.RenameField(
            model_name="provideravailabletimes",
            old_name="c_id",
            new_name="c",
        ),
    ]
